import 'package:flutter/material.dart';
import 'package:glass_forge_workbench/features/blend/presentation/views/blend_view.dart';
import 'package:glass_forge_workbench/features/components/presentation/views/components_view.dart';
import 'package:glass_forge_workbench/features/components/presentation/views/playground_view.dart';
import 'package:glass_forge_workbench/features/gallery/presentation/views/gallery_view.dart';
import 'package:glass_forge_workbench/features/lab/presentation/views/lab_view.dart';
import 'package:glass_forge_workbench/features/material_studio/presentation/views/material_studio_view.dart';
import 'package:glass_forge_workbench/features/motion/presentation/views/motion_view.dart';
import 'package:glass_forge_workbench/features/sampling_probe/presentation/views/sampling_probe_view.dart';
import 'package:glass_forge_workbench/features/shell/presentation/views/workbench_shell.dart';
import 'package:glass_forge_workbench/features/showcase/presentation/views/showcase_view.dart';
import 'package:glass_forge_workbench/features/tiers/presentation/views/tiers_view.dart';
import 'package:glass_forge_workbench/utils/enums/component_id.dart';
import 'package:glass_forge_workbench/utils/enums/lab_tool.dart';
import 'package:glass_forge_workbench/utils/widgets/tool/lab_tool_frame.dart';
import 'package:go_router/go_router.dart';

part 'router.dart';
part 'routes.dart';
